<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';Auth::requireLogin();header('Content-Type: application/json; charset=utf-8');
$modo=(string)($_GET['modo']??'buscar');
if($modo==='reverso'){$lat=filter_input(INPUT_GET,'lat',FILTER_VALIDATE_FLOAT);$lng=filter_input(INPUT_GET,'lng',FILTER_VALIDATE_FLOAT);if($lat===false||$lat===null||$lng===false||$lng===null||$lat<-90||$lat>90||$lng<-180||$lng>180){http_response_code(422);echo json_encode(['erro'=>'Localização inválida.'],JSON_UNESCAPED_UNICODE);exit;}$url='https://photon.komoot.io/reverse?lat='.rawurlencode((string)$lat).'&lon='.rawurlencode((string)$lng).'&limit=1';}
else{$consulta=trim((string)($_GET['q']??''));if(mb_strlen($consulta)<3){echo json_encode(['enderecos'=>[]],JSON_UNESCAPED_UNICODE);exit;}$url='https://photon.komoot.io/api/?q='.rawurlencode(mb_substr($consulta,0,160)).'&limit=6&lat=-14.235&lon=-51.9253';}
$resposta=false;$status=0;if(function_exists('curl_init')){$c=curl_init($url);curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>12,CURLOPT_USERAGENT=>'GeoPharma/1.4 (+https://geopharma.ameservice.com.br)',CURLOPT_HTTPHEADER=>['Accept: application/json']]);$resposta=curl_exec($c);$status=(int)curl_getinfo($c,CURLINFO_HTTP_CODE);curl_close($c);}else{$ctx=stream_context_create(['http'=>['timeout'=>12,'ignore_errors'=>true,'header'=>"User-Agent: GeoPharma/1.4 (+https://geopharma.ameservice.com.br)\r\nAccept: application/json\r\n"]]);$resposta=@file_get_contents($url,false,$ctx);if(isset($http_response_header[0])&&preg_match('/\s(\d{3})\s/',$http_response_header[0],$m))$status=(int)$m[1];}
if($resposta===false||$status!==200){http_response_code(502);echo json_encode(['erro'=>'O serviço de endereços não respondeu agora.'],JSON_UNESCAPED_UNICODE);exit;}
$dados=json_decode($resposta,true);$enderecos=[];foreach(($dados['features']??[]) as $feature){$p=$feature['properties']??[];$coordenadas=$feature['geometry']['coordinates']??[];if(count($coordenadas)<2)continue;$partes=array_values(array_unique(array_filter([$p['name']??null,$p['street']??null,$p['housenumber']??null,$p['district']??$p['locality']??null,$p['city']??null,$p['state']??null,$p['country']??null])));$rotulo=implode(', ',$partes);if($rotulo==='')continue;$enderecos[]=['rotulo'=>$rotulo,'nome'=>(string)($p['name']??$p['street']??'Endereço'),'detalhe'=>implode(', ',array_filter([$p['district']??$p['locality']??null,$p['city']??null,$p['state']??null])),'latitude'=>(float)$coordenadas[1],'longitude'=>(float)$coordenadas[0]];}
echo json_encode(['enderecos'=>$enderecos,'fonte'=>'Photon / OpenStreetMap'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
