<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';Auth::requireLogin();header('Content-Type: application/json; charset=utf-8');
$lat=filter_input(INPUT_GET,'lat',FILTER_VALIDATE_FLOAT);$lng=filter_input(INPUT_GET,'lng',FILTER_VALIDATE_FLOAT);$raio=filter_input(INPUT_GET,'raio',FILTER_VALIDATE_INT)?:5000;
if($lat===false||$lat===null||$lng===false||$lng===null||$lat<-90||$lat>90||$lng<-180||$lng>180){http_response_code(422);echo json_encode(['erro'=>'Localização inválida.'],JSON_UNESCAPED_UNICODE);exit;}
$raio=max(500,min(20000,$raio));$query='[out:json][timeout:25];nwr["amenity"="pharmacy"](around:'.$raio.','.$lat.','.$lng.');out center tags;';$url='https://overpass-api.de/api/interpreter?data='.rawurlencode($query);
$resposta=false;$status=0;if(function_exists('curl_init')){$c=curl_init($url);curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_TIMEOUT=>30,CURLOPT_USERAGENT=>'GeoPharma/1.4 (+https://geopharma.ameservice.com.br)']);$resposta=curl_exec($c);$status=(int)curl_getinfo($c,CURLINFO_HTTP_CODE);curl_close($c);}else{$ctx=stream_context_create(['http'=>['timeout'=>30,'ignore_errors'=>true,'header'=>"User-Agent: GeoPharma/1.4 (+https://geopharma.ameservice.com.br)\r\n"]]);$resposta=@file_get_contents($url,false,$ctx);if(isset($http_response_header[0])&&preg_match('/\s(\d{3})\s/',$http_response_header[0],$m))$status=(int)$m[1];}
if($resposta===false||$status!==200){http_response_code(502);echo json_encode(['erro'=>'O OpenStreetMap não respondeu agora. Tente novamente em instantes.'],JSON_UNESCAPED_UNICODE);exit;}
$dados=json_decode($resposta,true);$oportunidades=[];foreach(($dados['elements']??[]) as $item){$tags=$item['tags']??[];$itemLat=$item['lat']??$item['center']['lat']??null;$itemLng=$item['lon']??$item['center']['lon']??null;if($itemLat===null||$itemLng===null)continue;$endereco=trim(implode(', ',array_filter([$tags['addr:street']??null,$tags['addr:housenumber']??null,$tags['addr:suburb']??null,$tags['addr:city']??null])));$cnpj=preg_replace('/\D+/','',(string)($tags['cnpj']??$tags['contact:cnpj']??$tags['ref:vatin']??''))??'';if(strlen($cnpj)!==14)$cnpj='';$oportunidades[]=['osm_id'=>($item['type']??'node').'/'.($item['id']??''),'nome'=>$tags['name']??'Farmácia sem nome informado','telefone'=>$tags['phone']??$tags['contact:phone']??'','endereco'=>$endereco,'cnpj'=>$cnpj,'latitude'=>(float)$itemLat,'longitude'=>(float)$itemLng,'capturado'=>false];}
$ids=array_column($oportunidades,'osm_id');$leads=[];if($ids){$marcas=implode(',',array_fill(0,count($ids),'?'));$q=Database::connection()->prepare('SELECT osm_id,cnpj FROM leads WHERE osm_id IN ('.$marcas.')');$q->execute($ids);foreach($q->fetchAll() as $lead)$leads[$lead['osm_id']]=$lead['cnpj'];}foreach($oportunidades as &$oportunidade){$oportunidade['capturado']=array_key_exists($oportunidade['osm_id'],$leads);if(($leads[$oportunidade['osm_id']]??'')!=='')$oportunidade['cnpj']=$leads[$oportunidade['osm_id']];}unset($oportunidade);
echo json_encode(['oportunidades'=>$oportunidades,'fonte'=>'OpenStreetMap'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
