<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';Auth::requireAdmin();$pageTitle='Documentação';$activeMenu='documentacao';require GEOPHARMA_ROOT.'/includes/header.php';require GEOPHARMA_ROOT.'/includes/page-start.php';
?>
<section class="docs-hero card border-0 shadow-sm mb-4">
    <div class="card-body p-4 p-lg-5"><span class="badge text-bg-success mb-3"><i class="bi bi-geo-alt-fill me-1"></i>GeoPharma</span><h2 class="display-6 fw-bold mb-3">Inteligência geográfica para prospecção de farmácias</h2><p class="lead text-secondary mb-0">O GeoPharma organiza a descoberta de oportunidades, o trabalho dos representantes e a conversão de farmácias em clientes em uma única plataforma responsiva.</p></div>
</section>

<div class="row g-4 mb-4">
    <div class="col-12 col-xl-7"><div class="card card-outline card-success h-100 shadow-sm"><div class="card-header"><h3 class="card-title"><i class="bi bi-check2-circle me-2"></i>O que o sistema já faz</h3></div><div class="card-body"><div class="row g-3 docs-feature-grid">
        <div class="col-12 col-md-6"><div class="docs-feature"><i class="bi bi-shield-lock"></i><div><strong>Acesso protegido</strong><span>Login, sessão segura, perfis e administração de usuários.</span></div></div></div>
        <div class="col-12 col-md-6"><div class="docs-feature"><i class="bi bi-phone"></i><div><strong>Uso em campo</strong><span>Interface responsiva, pensada prioritariamente para celular.</span></div></div></div>
        <div class="col-12 col-md-6"><div class="docs-feature"><i class="bi bi-map"></i><div><strong>Mapa comercial</strong><span>Busca por endereço ou localização atual, raio personalizado e rotas.</span></div></div></div>
        <div class="col-12 col-md-6"><div class="docs-feature"><i class="bi bi-building"></i><div><strong>Oportunidades reais</strong><span>Farmácias registradas no OpenStreetMap, sem geração de dados fictícios.</span></div></div></div>
        <div class="col-12 col-md-6"><div class="docs-feature"><i class="bi bi-bullseye"></i><div><strong>Gestão de leads</strong><span>Captura no mapa, bloqueio de duplicidade, pesquisa, filtros e funil comercial.</span></div></div></div>
        <div class="col-12 col-md-6"><div class="docs-feature"><i class="bi bi-arrow-repeat"></i><div><strong>Conversão em cliente</strong><span>Preserva contato, endereço, coordenadas e observações do lead.</span></div></div></div>
        <div class="col-12 col-md-6"><div class="docs-feature"><i class="bi bi-card-checklist"></i><div><strong>Cadastro empresarial</strong><span>Clientes, CNPJ, dados cadastrais, localização e situação do registro.</span></div></div></div>
        <div class="col-12 col-md-6"><div class="docs-feature"><i class="bi bi-clipboard-check"></i><div><strong>Visitas comerciais</strong><span>Registro de resultado, observações e próximo retorno.</span></div></div></div>
    </div></div></div></div>
    <div class="col-12 col-xl-5"><div class="card h-100 shadow-sm"><div class="card-header"><h3 class="card-title"><i class="bi bi-signpost-split me-2"></i>Fluxo operacional</h3></div><div class="card-body"><ol class="docs-flow mb-0"><li><span>1</span><div><strong>Descobrir</strong><small>Pesquisar farmácias por região e raio.</small></div></li><li><span>2</span><div><strong>Capturar</strong><small>Transformar a oportunidade em lead.</small></div></li><li><span>3</span><div><strong>Qualificar</strong><small>Confirmar CNPJ, contato e endereço.</small></div></li><li><span>4</span><div><strong>Trabalhar</strong><small>Registrar contato, visita e negociação.</small></div></li><li><span>5</span><div><strong>Converter</strong><small>Criar o cliente mantendo o histórico.</small></div></li></ol></div></div></div>
</div>

<div class="card card-outline card-warning shadow-sm mb-4"><div class="card-header"><h3 class="card-title"><i class="bi bi-database-exclamation me-2"></i>Origem e segurança dos dados</h3></div><div class="card-body"><div class="row g-4"><div class="col-12 col-lg-6"><h4 class="h6 fw-bold">Situação atual</h4><p class="text-secondary mb-0">As oportunidades são consultadas no OpenStreetMap. São registros geográficos reais e úteis para prospecção, mas a fonte é colaborativa: uma empresa pode estar desatualizada, sem telefone ou sem CNPJ. Por isso, o representante deve confirmar os dados antes da conversão.</p></div><div class="col-12 col-lg-6"><h4 class="h6 fw-bold">Resultado mais confiável</h4><p class="text-secondary mb-0">Para apresentar CNPJ, situação cadastral, CNAE e endereço oficial de cada filial, é necessário contratar uma API empresarial com licença de uso comercial e pesquisa avançada. O GeoPharma deve cruzar nome, CEP, endereço e município e somente aceitar correspondências seguras.</p></div></div></div></div>

<div class="row g-4 mb-4">
    <div class="col-12 col-lg-6"><div class="card h-100 shadow-sm"><div class="card-header"><h3 class="card-title"><i class="bi bi-cloud-check me-2"></i>Infraestrutura necessária</h3></div><div class="card-body"><ul class="docs-checklist mb-0"><li><i class="bi bi-check-circle-fill"></i><span><strong>Servidor de aplicação</strong><small>PHP 8.2 ou superior, acesso HTTPS externo, armazenamento e tarefas agendadas.</small></span></li><li><i class="bi bi-check-circle-fill"></i><span><strong>Banco MySQL ou MariaDB</strong><small>Ambiente protegido, capacidade de crescimento e acesso restrito.</small></span></li><li><i class="bi bi-check-circle-fill"></i><span><strong>Domínio e certificado SSL</strong><small>Navegação segura e funcionamento confiável da geolocalização.</small></span></li><li><i class="bi bi-check-circle-fill"></i><span><strong>Backups automáticos</strong><small>Cópias do banco e dos arquivos com política de restauração testada.</small></span></li><li><i class="bi bi-check-circle-fill"></i><span><strong>Monitoramento</strong><small>Disponibilidade, erros, consumo de recursos e alertas operacionais.</small></span></li></ul></div></div></div>
    <div class="col-12 col-lg-6"><div class="card h-100 shadow-sm"><div class="card-header"><h3 class="card-title"><i class="bi bi-key me-2"></i>Serviços a contratar</h3></div><div class="card-body"><ul class="docs-checklist mb-0"><li><i class="bi bi-check-circle-fill"></i><span><strong>API de dados empresariais</strong><small>Pesquisa por CNAE, nome, cidade e CEP, consulta de filial e permissão comercial.</small></span></li><li><i class="bi bi-check-circle-fill"></i><span><strong>Mapas e geocodificação com SLA</strong><small>Recomendado quando o volume ultrapassar o uso permitido nos serviços públicos.</small></span></li><li><i class="bi bi-check-circle-fill"></i><span><strong>E-mail transacional</strong><small>Recuperação de senha, notificações e comunicações automáticas.</small></span></li><li><i class="bi bi-check-circle-fill"></i><span><strong>Serviço de observabilidade</strong><small>Registro centralizado de falhas, desempenho e auditoria técnica.</small></span></li><li><i class="bi bi-check-circle-fill"></i><span><strong>Suporte e continuidade</strong><small>Responsável técnico, atualizações, correções e atendimento aos clientes.</small></span></li></ul></div></div></div>
</div>

<div class="card card-outline card-primary shadow-sm mb-4"><div class="card-header"><h3 class="card-title"><i class="bi bi-rocket-takeoff me-2"></i>Requisitos para comercialização</h3></div><div class="card-body"><div class="table-responsive crud-table-wrapper"><table class="table align-middle mb-0 docs-table"><thead><tr><th>Área</th><th>O que precisa ser preparado</th><th>Objetivo</th></tr></thead><tbody><tr><td><strong>Empresas contratantes</strong></td><td>Separação segura dos dados de cada organização e seus representantes.</td><td>Atender vários clientes sem mistura de informações.</td></tr><tr><td><strong>Planos e licenças</strong></td><td>Limites de usuários, regiões, consultas e recursos por assinatura.</td><td>Criar receita recorrente e controlar consumo.</td></tr><tr><td><strong>Gestão comercial</strong></td><td>Metas, territórios, responsáveis, relatórios e indicadores reais.</td><td>Demonstrar retorno e produtividade.</td></tr><tr><td><strong>Auditoria</strong></td><td>Histórico de alterações, capturas, conversões e acessos.</td><td>Dar rastreabilidade e confiança.</td></tr><tr><td><strong>Privacidade</strong></td><td>Termos de uso, política de privacidade, retenção e atendimento à LGPD.</td><td>Operar comercialmente com responsabilidade.</td></tr><tr><td><strong>Operação</strong></td><td>Ambiente de testes, produção, backups, monitoramento e suporte.</td><td>Garantir estabilidade para clientes pagantes.</td></tr></tbody></table></div></div></div>

<div class="alert alert-success d-flex gap-3 align-items-start mb-0" role="note"><i class="bi bi-lightbulb-fill fs-4"></i><div><strong>Posicionamento do produto</strong><p class="mb-0 mt-1">O GeoPharma não é apenas um mapa: é um processo comercial para descobrir, distribuir, acompanhar e converter oportunidades do varejo farmacêutico. A qualidade da fonte empresarial, a organização dos territórios e o acompanhamento dos resultados são os principais diferenciais para gerar valor aos clientes.</p></div></div>
<?php require GEOPHARMA_ROOT.'/includes/page-end.php';require GEOPHARMA_ROOT.'/includes/footer.php';
