CREATE DATABASE IF NOT EXISTS geopharma CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE geopharma;

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    perfil ENUM('administrador', 'vendedor') NOT NULL DEFAULT 'vendedor',
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome_fantasia VARCHAR(200),
    razao_social VARCHAR(200),
    cnpj VARCHAR(18) UNIQUE,
    cep VARCHAR(10), logradouro VARCHAR(200), numero VARCHAR(30), bairro VARCHAR(120), cidade VARCHAR(120), uf CHAR(2),
    latitude DECIMAL(10,7), longitude DECIMAL(10,7), ativo TINYINT(1) NOT NULL DEFAULT 1,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

