<?php $editando=isset($cliente['id']); ?>
<?php if($erros):?><div class="alert alert-danger" role="alert"><strong><i class="bi bi-exclamation-triangle me-2"></i>Confira os campos:</strong><ul class="mb-0 mt-2"><?php foreach($erros as $erro):?><li><?= htmlspecialchars($erro) ?></li><?php endforeach;?></ul></div><?php endif;?>
<form method="post" class="card card-outline card-success shadow-sm" data-cliente-form>
<input type="hidden" name="csrf_token" value="<?= htmlspecialchars(Csrf::token()) ?>">
<div class="card-header"><h3 class="card-title"><i class="bi bi-building me-2"></i>Dados do cliente</h3></div>
<div class="card-body"><div class="row g-3">
<div class="col-12"><label for="documento" class="form-label">CNPJ <span class="text-danger">*</span></label><div class="input-group"><span class="input-group-text"><i class="bi bi-card-text"></i></span><input type="text" inputmode="numeric" class="form-control" id="documento" name="documento" value="<?= htmlspecialchars($dados['documento']) ?>" maxlength="18" required><button type="button" class="btn btn-outline-success" data-consultar-cnpj><i class="bi bi-search me-1"></i>Consultar CNPJ</button></div><div class="form-text" data-cnpj-status>Ao completar o CNPJ, os dados públicos serão preenchidos automaticamente.</div></div>
<div class="col-12 col-lg-7"><label for="razao_social" class="form-label">Nome / razão social <span class="text-danger">*</span></label><input type="text" class="form-control" id="razao_social" name="razao_social" value="<?= htmlspecialchars($dados['razao_social']) ?>" maxlength="180" required></div>
<div class="col-12 col-lg-5"><label for="nome_fantasia" class="form-label">Nome fantasia</label><input type="text" class="form-control" id="nome_fantasia" name="nome_fantasia" value="<?= htmlspecialchars($dados['nome_fantasia']) ?>" maxlength="180"></div>
<div class="col-12 col-md-5"><label for="telefone" class="form-label">Telefone</label><div class="input-group"><span class="input-group-text"><i class="bi bi-telephone"></i></span><input type="tel" class="form-control" id="telefone" name="telefone" value="<?= htmlspecialchars($dados['telefone']) ?>" maxlength="20"></div></div>
<div class="col-12 col-md-7"><label for="email" class="form-label">E-mail</label><div class="input-group"><span class="input-group-text"><i class="bi bi-envelope"></i></span><input type="email" class="form-control" id="email" name="email" value="<?= htmlspecialchars($dados['email']) ?>" maxlength="190"></div></div>
</div><hr class="my-4"><h4 class="h6 fw-bold mb-3"><i class="bi bi-geo-alt me-2 text-success"></i>Endereço e localização</h4><div class="row g-3">
<div class="col-12 col-sm-4 col-lg-3"><label for="cep" class="form-label">CEP</label><input type="text" inputmode="numeric" class="form-control" id="cep" name="cep" value="<?= htmlspecialchars($dados['cep']) ?>" maxlength="9"></div>
<div class="col-12 col-sm-8 col-lg-7"><label for="logradouro" class="form-label">Logradouro</label><input type="text" class="form-control" id="logradouro" name="logradouro" value="<?= htmlspecialchars($dados['logradouro']) ?>" maxlength="180"></div>
<div class="col-12 col-sm-4 col-lg-2"><label for="numero" class="form-label">Número</label><input type="text" class="form-control" id="numero" name="numero" value="<?= htmlspecialchars($dados['numero']) ?>" maxlength="20"></div>
<div class="col-12 col-md-4"><label for="complemento" class="form-label">Complemento</label><input type="text" class="form-control" id="complemento" name="complemento" value="<?= htmlspecialchars($dados['complemento']) ?>" maxlength="100"></div>
<div class="col-12 col-md-4"><label for="bairro" class="form-label">Bairro</label><input type="text" class="form-control" id="bairro" name="bairro" value="<?= htmlspecialchars($dados['bairro']) ?>" maxlength="100"></div>
<div class="col-9 col-md-3"><label for="cidade" class="form-label">Cidade</label><input type="text" class="form-control" id="cidade" name="cidade" value="<?= htmlspecialchars($dados['cidade']) ?>" maxlength="100"></div>
<div class="col-3 col-md-1"><label for="estado" class="form-label">UF</label><input type="text" class="form-control text-uppercase" id="estado" name="estado" value="<?= htmlspecialchars($dados['estado']) ?>" maxlength="2"></div>
<div class="col-12 col-md-6"><label for="latitude" class="form-label">Latitude</label><input type="text" inputmode="decimal" class="form-control" id="latitude" name="latitude" value="<?= htmlspecialchars((string)$dados['latitude']) ?>" placeholder="Ex.: -23.5505200"></div>
<div class="col-12 col-md-6"><label for="longitude" class="form-label">Longitude</label><input type="text" inputmode="decimal" class="form-control" id="longitude" name="longitude" value="<?= htmlspecialchars((string)$dados['longitude']) ?>" placeholder="Ex.: -46.6333080"></div>
<div class="col-12"><label for="observacoes" class="form-label">Observações</label><textarea class="form-control" id="observacoes" name="observacoes" rows="3" maxlength="3000"><?= htmlspecialchars($dados['observacoes']) ?></textarea></div>
<div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" role="switch" id="ativo" name="ativo" value="1" <?= $dados['ativo']?'checked':'' ?>><label class="form-check-label" for="ativo">Cliente ativo</label></div></div>
</div></div>
<div class="card-footer d-flex flex-column-reverse flex-sm-row justify-content-end gap-2"><a href="/clientes/" class="btn btn-default">Cancelar</a><button type="submit" class="btn btn-success" data-loading-label="Salvando..."><i class="bi bi-check-lg me-1"></i>Salvar cliente</button></div>
</form>
