<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php'; Auth::requireAdmin();
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)?:0;$pdo=Database::connection();$q=$pdo->prepare('SELECT id,nome,login,email,perfil,ativo FROM usuarios WHERE id=:id');$q->execute(['id'=>$id]);$usuario=$q->fetch();if(!$usuario){http_response_code(404);exit('Usuário não encontrado.');}
$dados=['nome'=>$usuario['nome'],'login'=>$usuario['login'],'email'=>$usuario['email'],'perfil'=>$usuario['perfil'],'ativo'=>(bool)$usuario['ativo']];$erros=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 $dados=['nome'=>trim((string)($_POST['nome']??'')),'login'=>mb_strtolower(trim((string)($_POST['login']??''))),'email'=>mb_strtolower(trim((string)($_POST['email']??''))),'perfil'=>(string)($_POST['perfil']??''),'ativo'=>isset($_POST['ativo'])];$senha=(string)($_POST['senha']??'');
 if(!Csrf::validate($_POST['csrf_token']??null))$erros[]='A sessão expirou. Atualize a página.';if(mb_strlen($dados['nome'])<3)$erros[]='Informe o nome completo.';if(!preg_match('/^[a-z0-9._-]{3,60}$/',$dados['login']))$erros[]='O login deve ter entre 3 e 60 caracteres válidos.';if(!filter_var($dados['email'],FILTER_VALIDATE_EMAIL))$erros[]='Informe um e-mail válido.';if(!in_array($dados['perfil'],['administrador','gestor','vendedor'],true))$erros[]='Selecione um perfil válido.';if($senha!==''&&strlen($senha)<8)$erros[]='A nova senha deve ter pelo menos 8 caracteres.';if($id===(int)(Auth::user()['id']??0)&&(!$dados['ativo']||$dados['perfil']!=='administrador'))$erros[]='Você não pode remover seu próprio acesso administrativo.';
 if(!$erros){$q=$pdo->prepare('SELECT COUNT(*) FROM usuarios WHERE (login=:login OR email=:email) AND id<>:id');$q->execute(['login'=>$dados['login'],'email'=>$dados['email'],'id'=>$id]);if((int)$q->fetchColumn()>0)$erros[]='Já existe outro usuário com esse login ou e-mail.';else{$sql='UPDATE usuarios SET nome=:nome,login=:login,email=:email,perfil=:perfil,ativo=:ativo';$params=['nome'=>$dados['nome'],'login'=>$dados['login'],'email'=>$dados['email'],'perfil'=>$dados['perfil'],'ativo'=>$dados['ativo']?1:0,'id'=>$id];if($senha!==''){$sql.=',senha_hash=:senha';$params['senha']=password_hash($senha,PASSWORD_DEFAULT);}$sql.=' WHERE id=:id';$pdo->prepare($sql)->execute($params);if($id===(int)(Auth::user()['id']??0)){$_SESSION['usuario']['nome']=$dados['nome'];$_SESSION['usuario']['login']=$dados['login'];}header('Location: /usuarios/?resultado=atualizado');exit;}}
}
$pageTitle='Editar usuário';$activeMenu='usuarios';require GEOPHARMA_ROOT.'/includes/header.php';require GEOPHARMA_ROOT.'/includes/page-start.php';require __DIR__.'/_form.php';require GEOPHARMA_ROOT.'/includes/page-end.php';require GEOPHARMA_ROOT.'/includes/footer.php';
