<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';Auth::requireLogin();require __DIR__.'/_helpers.php';$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)?:0;$pdo=Database::connection();$q=$pdo->prepare('SELECT * FROM leads WHERE id=:id');$q->execute(['id'=>$id]);$lead=$q->fetch();if(!$lead){header('Location: /leads/?resultado=erro');exit;}$erros=[];
$campos=['cnpj','razao_social','nome_fantasia','telefone','email','cep','logradouro','numero','complemento','bairro','cidade','estado','status','observacoes'];
if($_SERVER['REQUEST_METHOD']==='POST'){if(!Csrf::validate($_POST['csrf_token']??null))$erros[]='A sessão expirou. Atualize a página.';foreach($campos as $campo)$lead[$campo]=trim((string)($_POST[$campo]??''));$lead['cnpj']=preg_replace('/\D+/','',$lead['cnpj'])??'';$lead['cep']=preg_replace('/\D+/','',$lead['cep'])??'';if(mb_strlen($lead['nome_fantasia'])<2)$erros[]='Informe o nome da farmácia.';if(!isset(leadStatus()[$lead['status']]))$erros[]='Selecione um status válido.';if($lead['cnpj']!==''&&!leadCnpjValido($lead['cnpj']))$erros[]='Informe um CNPJ válido.';if(!$erros){$duplicado=$pdo->prepare('SELECT COUNT(*) FROM leads WHERE cnpj=:cnpj AND id<>:id');$duplicado->execute(['cnpj'=>$lead['cnpj']?:null,'id'=>$id]);if($lead['cnpj']!==''&&(int)$duplicado->fetchColumn()>0)$erros[]='Esse CNPJ já está vinculado a outro lead.';else{$sql='UPDATE leads SET cnpj=:cnpj,razao_social=:razao_social,nome_fantasia=:nome_fantasia,telefone=:telefone,email=:email,cep=:cep,logradouro=:logradouro,numero=:numero,complemento=:complemento,bairro=:bairro,cidade=:cidade,estado=:estado,status=:status,observacoes=:observacoes WHERE id=:id';$params=['id'=>$id];foreach($campos as $campo)$params[$campo]=$lead[$campo]!==''?$lead[$campo]:null;$pdo->prepare($sql)->execute($params);header('Location: /leads/?resultado=atualizado');exit;}}}
$pageTitle='Editar lead';$activeMenu='leads';require GEOPHARMA_ROOT.'/includes/header.php';require GEOPHARMA_ROOT.'/includes/page-start.php';?>
<?php if($erros):?><div class="alert alert-danger"><ul class="mb-0"><?php foreach($erros as $erro):?><li><?= htmlspecialchars($erro) ?></li><?php endforeach;?></ul></div><?php endif;?>
<form method="post" data-lead-form><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(Csrf::token()) ?>"><div class="card card-outline card-success shadow-sm"><div class="card-header"><h3 class="card-title">Dados do lead</h3></div><div class="card-body"><div class="row g-3">
<div class="col-12 col-md-4"><label class="form-label" for="documento">CNPJ</label><input class="form-control" id="documento" name="cnpj" value="<?= htmlspecialchars($lead['cnpj']??'') ?>" inputmode="numeric"><div class="form-text" data-cnpj-status>Ao completar o CNPJ, os dados oficiais serão consultados.</div></div>
<div class="col-12 col-md-4"><label class="form-label" for="nome_fantasia">Nome fantasia *</label><input class="form-control" id="nome_fantasia" name="nome_fantasia" value="<?= htmlspecialchars($lead['nome_fantasia']) ?>" required></div><div class="col-12 col-md-4"><label class="form-label" for="razao_social">Razão social</label><input class="form-control" id="razao_social" name="razao_social" value="<?= htmlspecialchars($lead['razao_social']??'') ?>"></div>
<div class="col-12 col-md-4"><label class="form-label" for="telefone">Telefone</label><input class="form-control" id="telefone" name="telefone" value="<?= htmlspecialchars($lead['telefone']??'') ?>"></div><div class="col-12 col-md-4"><label class="form-label" for="email">E-mail</label><input class="form-control" id="email" name="email" value="<?= htmlspecialchars($lead['email']??'') ?>"></div><div class="col-12 col-md-4"><label class="form-label" for="status">Status *</label><select class="form-select" id="status" name="status" required><?php foreach(leadStatus() as $valor=>$rotulo):?><option value="<?= $valor ?>" <?= $lead['status']===$valor?'selected':'' ?>><?= $rotulo ?></option><?php endforeach;?></select></div>
<div class="col-12 col-md-3"><label class="form-label" for="cep">CEP</label><input class="form-control" id="cep" name="cep" value="<?= htmlspecialchars($lead['cep']??'') ?>"></div><div class="col-12 col-md-6"><label class="form-label" for="logradouro">Endereço</label><input class="form-control" id="logradouro" name="logradouro" value="<?= htmlspecialchars($lead['logradouro']??'') ?>"></div><div class="col-12 col-md-3"><label class="form-label" for="numero">Número</label><input class="form-control" id="numero" name="numero" value="<?= htmlspecialchars($lead['numero']??'') ?>"></div><div class="col-12 col-md-4"><label class="form-label" for="complemento">Complemento</label><input class="form-control" id="complemento" name="complemento" value="<?= htmlspecialchars($lead['complemento']??'') ?>"></div><div class="col-12 col-md-3"><label class="form-label" for="bairro">Bairro</label><input class="form-control" id="bairro" name="bairro" value="<?= htmlspecialchars($lead['bairro']??'') ?>"></div><div class="col-12 col-md-3"><label class="form-label" for="cidade">Cidade</label><input class="form-control" id="cidade" name="cidade" value="<?= htmlspecialchars($lead['cidade']??'') ?>"></div><div class="col-12 col-md-2"><label class="form-label" for="estado">UF</label><input class="form-control" id="estado" name="estado" maxlength="2" value="<?= htmlspecialchars($lead['estado']??'') ?>"></div><div class="col-12"><label class="form-label" for="observacoes">Observações</label><textarea class="form-control" id="observacoes" name="observacoes" rows="4"><?= htmlspecialchars($lead['observacoes']??'') ?></textarea></div>
</div></div><div class="card-footer d-flex flex-column flex-sm-row justify-content-end gap-2"><a href="/leads/" class="btn btn-default">Cancelar</a><button class="btn btn-success" data-loading-label="Salvando..."><i class="bi bi-check-lg me-1"></i>Salvar lead</button></div></div></form>
<?php require GEOPHARMA_ROOT.'/includes/page-end.php';require GEOPHARMA_ROOT.'/includes/footer.php';
