<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';Auth::requireLogin();require __DIR__.'/_helpers.php';
$busca=trim((string)($_GET['busca']??''));$statusFiltro=trim((string)($_GET['status']??''));$paginaAtual=Pagination::currentPage();$pdo=Database::connection();$where=[];$params=[];
if($busca!==''){$where[]='(nome_fantasia LIKE :busca OR razao_social LIKE :busca OR cnpj LIKE :documento OR logradouro LIKE :busca)';$params['busca']='%'.$busca.'%';$params['documento']='%'.(preg_replace('/\D+/','',$busca)??'').'%';}if(isset(leadStatus()[$statusFiltro])){$where[]='status=:status';$params['status']=$statusFiltro;}$sqlWhere=$where?' WHERE '.implode(' AND ',$where):'';
$q=$pdo->prepare('SELECT COUNT(*) FROM leads'.$sqlWhere);$q->execute($params);$total=(int)$q->fetchColumn();$totalPaginas=Pagination::totalPages($total);$paginaAtual=min($paginaAtual,$totalPaginas);
$q=$pdo->prepare('SELECT id,nome_fantasia,razao_social,cnpj,telefone,logradouro,cidade,estado,status,cliente_id,criado_em FROM leads'.$sqlWhere.' ORDER BY criado_em DESC LIMIT :limite OFFSET :inicio');foreach($params as $k=>$v)$q->bindValue(':'.$k,$v);$q->bindValue(':limite',Pagination::PER_PAGE,PDO::PARAM_INT);$q->bindValue(':inicio',Pagination::offset($paginaAtual),PDO::PARAM_INT);$q->execute();$leads=$q->fetchAll();
$mensagens=['atualizado'=>['success','Lead atualizado com sucesso.'],'convertido'=>['success','Lead convertido em cliente.'],'excluido'=>['success','Lead excluído.'],'pendente'=>['warning','Informe e confirme o CNPJ antes de converter.'],'duplicado'=>['warning','Já existe um cliente com esse CNPJ.'],'erro'=>['danger','Não foi possível concluir a operação.']];$mensagem=$mensagens[$_GET['resultado']??'']??null;
$pageTitle='Leads';$activeMenu='leads';require GEOPHARMA_ROOT.'/includes/header.php';require GEOPHARMA_ROOT.'/includes/page-start.php';
?>
<?php if($mensagem):?><div class="alert alert-<?= $mensagem[0] ?> alert-dismissible fade show" role="alert"><?= htmlspecialchars($mensagem[1]) ?><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Fechar"></button></div><?php endif;?>
<div class="card card-outline card-success shadow-sm"><div class="card-header"><h3 class="card-title mb-0"><i class="bi bi-bullseye me-2"></i>Leads capturados no mapa</h3></div>
<div class="card-body border-bottom"><form method="get" class="row g-2"><div class="col-12 col-md"><div class="input-group"><span class="input-group-text"><i class="bi bi-search"></i></span><input class="form-control" type="search" name="busca" value="<?= htmlspecialchars($busca) ?>" placeholder="Nome, CNPJ ou endereço" aria-label="Pesquisar leads"></div></div><div class="col-12 col-md-3"><select class="form-select" name="status" aria-label="Filtrar por status"><option value="">Todos os status</option><?php foreach(leadStatus() as $valor=>$rotulo):?><option value="<?= $valor ?>" <?= $statusFiltro===$valor?'selected':'' ?>><?= $rotulo ?></option><?php endforeach;?></select></div><div class="col-12 col-md-auto d-grid"><button class="btn btn-outline-success" data-loading-label="Pesquisando...">Pesquisar</button></div></form></div>
<?php if(!$leads):?><div class="empty-state"><i class="bi bi-bullseye"></i><h4>Nenhum lead encontrado</h4><p>Abra uma farmácia no mapa e use “Capturar lead”.</p><a href="/mapa/" class="btn btn-success"><i class="bi bi-map me-1"></i>Abrir mapa</a></div><?php else:?><div class="table-responsive crud-table-wrapper"><table class="table table-hover align-middle mb-0 crud-table"><thead><tr><th>Lead</th><th>CNPJ</th><th>Contato</th><th>Status</th><th>Capturado em</th><th class="text-end">Ações</th></tr></thead><tbody><?php foreach($leads as $lead):?><tr><td><strong class="d-block"><?= htmlspecialchars($lead['nome_fantasia']) ?></strong><small class="text-secondary"><?= htmlspecialchars($lead['logradouro']?:trim(($lead['cidade']??'').' / '.($lead['estado']??''))) ?></small></td><td><?= $lead['cnpj']?htmlspecialchars(Formatter::cnpj($lead['cnpj'])):'<span class="badge text-bg-warning">Pendente</span>' ?></td><td><?= htmlspecialchars(Formatter::telefone($lead['telefone'])) ?></td><td><span class="badge <?= leadBadge($lead['status']) ?>"><?= htmlspecialchars(leadStatus()[$lead['status']]??$lead['status']) ?></span></td><td><?= date('d/m/Y H:i',strtotime($lead['criado_em'])) ?></td><td><div class="d-flex justify-content-end gap-2 crud-actions"><a class="btn btn-sm btn-outline-primary" href="/leads/edit.php?id=<?= (int)$lead['id'] ?>"><i class="bi bi-pencil"></i><span class="ms-1">Editar</span></a><?php if(!$lead['cliente_id']):?><form method="post" action="/leads/convert.php" onsubmit="return confirm('Converter este lead em cliente?');"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(Csrf::token()) ?>"><input type="hidden" name="id" value="<?= (int)$lead['id'] ?>"><button class="btn btn-sm btn-success" data-loading-label="Convertendo..."><i class="bi bi-arrow-repeat"></i><span class="ms-1">Converter</span></button></form><?php endif;?><form method="post" action="/leads/delete.php" onsubmit="return confirm('Excluir definitivamente este lead?');"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(Csrf::token()) ?>"><input type="hidden" name="id" value="<?= (int)$lead['id'] ?>"><button class="btn btn-sm btn-outline-danger" data-loading-label="Excluindo..."><i class="bi bi-trash"></i></button></form></div></td></tr><?php endforeach;?></tbody></table></div><?php endif;?><div class="card-footer text-secondary small"><?= $total ?> lead(s) encontrado(s)</div><?php require GEOPHARMA_ROOT.'/includes/pagination.php';?></div>
<?php require GEOPHARMA_ROOT.'/includes/page-end.php';require GEOPHARMA_ROOT.'/includes/footer.php';?>
